### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by gamepoet** [heftyfunseeker/scuba-steve#1]
I get this when just starting up atom with this package installed. :)

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [scuba-steve](https://github.com/heftyfunseeker/scuba-steve) package 0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'add' of undefined

```
At /Users/bscott/.atom/packages/scuba-steve/lib/scuba-steve.coffee:40

TypeError: Cannot read property 'add' of undefined
    at Object.startDive (/packages/scuba-steve/lib/scuba-steve.coffee:40:14)
    at /packages/scuba-steve/lib/scuba-steve.coffee:18:24
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -0:09.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-material-syntax 1.0.6 
atom-perforce 1.7.11 
build 0.68.0 
build-cmake 0.10.1 
busy 0.7.0 
clang-format 1.29.0 
dash 1.7.1 
editorconfig 2.2.2 
file-icons 2.1.10 
language-actionscript3 0.3.0 
language-batchfile 0.7.0 
language-cmake 0.3.0 
language-glsl 2.0.1 
language-hcl 0.4.0 
language-lua 0.9.11 
language-swift 0.5.0 
language-terraform 0.8.1 
monokai-dark 1.3.0 
monokai-slate 0.6.0 
pen-paper-coffee-syntax 0.14.9 
predawn-syntax 1.0.4 
predawn-ui 1.0.7 
project-manager 3.3.5 
release-notes 0.53.0 
scuba-steve 0.5.0 
sort-lines 0.14.0 
ssh-config 0.10.1 
sync-settings 0.8.2 
```

**Comment by heftyfunseeker** [comment]
This should be fixed now (as of 0.5.1).
